Métodos Booleanos

Any - Verifica se um ou is valores booleanos são True

All - Verifica se todos os valores são True

In [2]:
import numpy as np
a = np.array([True,False,False,True])
a.any()
a.all()

False

Os métodos anteriores também podem ser usados em arrays não booleanos, onde True é retornado para valores diferentes de 0.

In [4]:
a = np.array([1,2,0,0,0])
a.any()
a.all()

False

Ordenação

Sort - Assim como listas em python, um array NumPy pode ser ordenado com sort.
Para arrays multidimensionais, pode-se ordenar especificando o eixo, sendo 1 para horizontal e 0 para vertical.

In [11]:
a = np.array([8,9,23,44,1,-1,-0.8,6,0])
a.sort()
a

array([-1. , -0.8,  0. ,  1. ,  6. ,  8. ,  9. , 23. , 44. ])

In [18]:
b = np.array([[1,4,3],[55,4,0],[0.2,-3,19]])
b1 = b.sort(1)
b0 = b.sort(0)
b

array([[-3. ,  0.2,  4. ],
       [ 0. ,  3. , 19. ],
       [ 1. ,  4. , 55. ]])

np.sort devolve uma cópia ordenada do array, ao invés de modificá-lo in-place.

In [21]:
a = np.array([1,22,6,9,0,-1])
b = np.sort(a)
b

array([-1,  0,  1,  6,  9, 22])