Uma função universal é aquela capaz de fazer operações em todos os elementos de um ndarray.
Alguns exemplos de Ufuncs unárias são 'sqrt' e 'exp'.
Ufuncs binárias aceitam dois arrays e exemplos dessas funções são 'maximum' e 'add'.

In [5]:
import numpy as np

a = np.arange(10)
np.sqrt(a) #Raiz quadrada
np.exp(a) #Função exponencial

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [11]:
b = np.array([2.5,33,88,90,0,2,12,1,4,30])
b
np.maximum(a,b)


array([ 2.5, 33. , 88. , 90. ,  4. ,  5. , 12. ,  7. ,  8. , 30. ])

A função 'modf' traz a parte fracionária e inteira de todos os elementos de um array.

In [18]:
c = np.random.randn(6)
fracao,inteiro = np.modf(c)
inteiro
fracao

array([ 0.45709778, -0.59700067,  0.66965526,  0.06396855, -0.89393426,
       -0.09933504])

In [23]:
np.fabs(c) #Retorna o valor absoluto, ou seja, sem o sinal negativo
np.sign(c) #Retorna o sinal de cada elemento 
np.isnan(c) #Se cada valor é 'Not a Number'
np.isfinite(c) #Se é finito 

array([ True,  True,  True,  True,  True,  True])