A indexação é amplamente utilizada, pois muitas vezes você vai querer selecionar apenas uma parte específica do array.
Os arrays unidimensionais tem um comportamento parecido com as listas em Python:

In [9]:
import numpy as np
arr_uni = np.arange(10)
arr_uni
arr_uni.ndim

array([1, 3])

In [10]:
arr_uni[3:7]
arr_uni[1:5:2]
arr_uni[2]

2

Quando atribuímos um valor a um slice (fatia), o mesmo sofrerá broadcast. Ou seja, o valor será propagado para todos os valores pertencentes ao slice:

In [12]:
arr_uni[4:7]=45
arr_uni

array([ 0,  1,  2,  3, 45, 45, 45,  7,  8,  9])

Após essa alteração, se for alterar novamente, o resultado será refletido a partir da última atualização:


In [13]:
arr_uni[0]=60
arr_uni

array([60,  1,  2,  3, 45, 45, 45,  7,  8,  9])

In [18]:
arr_uni[5:8].copy()

array([45, 45,  7])

Em um array bidimensional, os elementos em cada índice não são mais escalares, mas sim arrays unidimensionais:

In [21]:
a_bid = np.array([[1,2,3],[4,5,6],[7,8,9]])
a_bid
a_bid[1] # Retorna a segunda lista [4,5,6]
a_bid[1][2] # Retorna o elemento '6' na segunda lista

6

In [26]:
a_multi = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
a_multi[0] #Retorna o primeiro array bidimensional
a_multi[1,0] #Retorna [7,8,9]
a_multi[1,1,2] #Retorna 12

12

Podemos copiar alguns dados em uma variável e posteriormente mudar esses valores:

In [27]:
old_values = a_multi[0,0].copy()
old_values

array([1, 2, 3])

In [32]:
a_multi[0,0]=32
a_multi

array([[[32, 32, 32],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [31]:
a_multi[0,0]=old_values
a_multi

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])