Vamos suport que cada nome do array "nomes" corresponda a uma linha do array "dados". Podemos selecionar todas as linhas que correspondem ao nome "Ana" com o símbolo de atribuição "=="

In [8]:
import numpy as np
nomes = np.array(['Ana','Maria','Ana','Ana Julia','Vitoria'])
dados = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
nomes=='Ana'
dados[nomes=='Ana']

array([[1, 2, 3],
       [7, 8, 9]])

OBS: O array booleano precisa ter o mesmo tamanho do array a ser indexado!

In [17]:
dados[nomes=='Ana', 1]
dados[nomes!='Ana']
a = (nomes=='Ana') | (nomes=='Maria')
dados[a]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

As palavras "and" e "or" não funcionam para indexação booleana. Deve-se utilizar & e |

In [19]:
dados[dados>=5]=0
dados

array([[1, 2, 3],
       [4, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [21]:
dados[nomes=='Ana']=9430
dados

array([[9430, 9430, 9430],
       [   4,    0,    0],
       [9430, 9430, 9430],
       [   0,    0,    0],
       [   0,    0,    0]])